# This example show how to:
#   - multiple jobs in the same workflow
#   - specify the working directory
#   - read secret values from github

name: Show secrets

on:
  push:
    branches:
      - master

jobs:
  job-show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: show secret defined on github repo
        run: echo ${{ secrets.MY_SECRET }}

  job-show-app-token:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./github-action-basic
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: |
          APP_TOKEN=$(node cli.js rdstr)
          echo "APP_TOKEN=$APP_TOKEN" >> $GITHUB_ENV
          echo "::add-mask::$APP_TOKEN"
      - run: echo app-token $APP_TOKEN
