# This example show how to:
#   - build and push docker image to docker hub

name: Build and push Docker image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: github-action-basic

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        id: docker_build
        with:
          context: ../../github-action-basic
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/nodejsapp-github-action
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
